spring:
  application:
    name: store-winrecord
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/winrecord} 
    username: ${DATABASE_USERNAME:winrecord_user} 
    password: ${DATABASE_PASSWORD:winrecord_pass} 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      base-path: /winrecord/actuator
      exposure:
        include: ['info', 'health', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8080} # Atualize se necessário
